server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: shedlock-poc
  datasource:
    url: jdbc:postgresql://localhost:5432/shedlock_poc
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  sql:
    init:
      mode: always
      continue-on-error: true

# --- Configuration du POC ---
batch:
  simulated-duration-minutes: ${BATCH_DURATION_MINUTES:20}

# --- Logging ---
logging:
  level:
    root: INFO
    com.poc.shedlock: DEBUG
    net.javacrumbs.shedlock: INFO
